<a href="https://colab.research.google.com/github/iishikawalia/Numpy-Learning/blob/main/NumpyArrayCreationMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
#1-D array
arr1d=np.array([10,20,3040,50,66,665,4,4])
print(arr1d)
#matrix= 2-D array
arr2d=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr2d)
matrix=np.array( [[2,4,6],
                  [8,10,20]])
print(matrix)
#multiple layers of storage data


[  10   20 3040   50   66  665    4    4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 20]]


In [6]:
import numpy as np
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [24]:
import numpy as np
filled_Array=np.full((2,5),7)
print(filled_Array)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [28]:
#creating sequences of numbers in numpy - arange function
import numpy as np
#arange(start, stop, step)
#returns numpy array
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [31]:
#creating identity matrices
#it is a square matrix with 1 no diagonal elements and 0 else where
import numpy as np
identity_matrix=np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np